### ISSUE TITLE
convert.rb skips all org files (unsupported file extension)

### ISSUE THREAD

**Issue by atimofeev** [goshatch/orgroam_to_obsidian#13]
```console
❯ ./convert.rb
Skipping (unsupported file extension): Caching
Skipping (unsupported file extension): Tech Projects
Skipping (unsupported file extension): Docker
Skipping (unsupported file extension): Python
Skipping (unsupported file extension): AI
Skipping (unsupported file extension): GitHub Actions
Skipping (unsupported file extension): Linux Kernel
Skipping (unsupported file extension): Virtual Private Network
Skipping (unsupported file extension): cgroups
Skipping (unsupported file extension): Sites
Skipping (unsupported file extension): Practices
Skipping (unsupported file extension): Terraform
Skipping (unsupported file extension): ChatGPT Prompts
Skipping (unsupported file extension): HTTP
Skipping (unsupported file extension): Text Manipulation
Skipping (unsupported file extension): Linux System Services
Skipping (unsupported file extension): Kubernetes in 3.5h
Skipping (unsupported file extension): Functional Programming
Skipping (unsupported file extension): Bash
Skipping (unsupported file extension): Hack your brain with Obsidian.md
Skipping (unsupported file extension): Relational Databases
Skipping (unsupported file extension): Linux Processes
Skipping (unsupported file extension): Work
Skipping (unsupported file extension): Simple Storage Service
Skipping (unsupported file extension): Leisure
Skipping (unsupported file extension): Logic Programming
Skipping (unsupported file extension): Hybrid Cloud
Skipping (unsupported file extension): Pre-signed URLs
Skipping (unsupported file extension): Managed K8s in Cloud
Skipping (unsupported file extension): LXC
Skipping (unsupported file extension): namespaces
Skipping (unsupported file extension): Leaky Bucket Algorithm
Skipping (unsupported file extension): Reactive Programming
Skipping (unsupported file extension): AI Tools
Skipping (unsupported file extension): Kubernetes
Skipping (unsupported file extension): DNS
Skipping (unsupported file extension): Redis
Skipping (unsupported file extension): Cloud
Skipping (unsupported file extension): Extended Mind
Skipping (unsupported file extension): Client-server communication
Skipping (unsupported file extension): Mental Health Tests
Skipping (unsupported file extension): Subnets & CIDR
Skipping (unsupported file extension): Uncategorized
Skipping (unsupported file extension): DevSecOps
Skipping (unsupported file extension): Meetings
Skipping (unsupported file extension): Structured Programming
Skipping (unsupported file extension): Prometheus
Skipping (unsupported file extension): Games
Skipping (unsupported file extension): Ansible
Skipping (unsupported file extension): Graph Databases
Skipping (unsupported file extension): Tech Stack
Skipping (unsupported file extension): Ender 3 bootloader
Skipping (unsupported file extension): Bike
Skipping (unsupported file extension): Deployment Strategies
Skipping (unsupported file extension): Health
Skipping (unsupported file extension): Thundering Herd
Skipping (unsupported file extension): Version Control
Skipping (unsupported file extension): GitOps
Skipping (unsupported file extension): MongoDB
Skipping (unsupported file extension): HTTP Status Codes
Skipping (unsupported file extension): Music
Skipping (unsupported file extension): Simple Queue Service
Skipping (unsupported file extension): Gitlab CI
Skipping (unsupported file extension): Stash Tools
Skipping (unsupported file extension): Regular Expressions
Skipping (unsupported file extension): Kubernetes Essentials
Skipping (unsupported file extension): Programming
Skipping (unsupported file extension): Operation Systems
Skipping (unsupported file extension): Content Delivery Network
Skipping (unsupported file extension): Elastic Block Storage
Skipping (unsupported file extension): PostgreSQL
Skipping (unsupported file extension): Interviews
Skipping (unsupported file extension): Network Troubleshooting
Skipping (unsupported file extension): Object Oriented Programming
Skipping (unsupported file extension): Infrastructure as Code
Skipping (unsupported file extension): Procedural Programming
Skipping (unsupported file extension): Mastering AWS CloudFormation
Skipping (unsupported file extension): Bicycle Buy List
Skipping (unsupported file extension): Helm
Skipping (unsupported file extension): 15 Python Libs You Should use
Skipping (unsupported file extension): AWS Billing, Budget Alerts and Costs
Skipping (unsupported file extension): Debt
Skipping (unsupported file extension): Subscriptions
Skipping (unsupported file extension): Wallpaper Pics
Skipping (unsupported file extension): Programming Design Patterns
Skipping (unsupported file extension): AutoGPT
Skipping (unsupported file extension): AWS Best Practices
Skipping (unsupported file extension): Books
Skipping (unsupported file extension): Data Structures
Skipping (unsupported file extension): Linux Under The Hood
Skipping (unsupported file extension): Mental Health
Skipping (unsupported file extension): vim
Skipping (unsupported file extension): IAM Core Concepts
Skipping (unsupported file extension): Ideas
Skipping (unsupported file extension): tentatrice_jewelry
Skipping (unsupported file extension): Music Buy List
Skipping (unsupported file extension): KlackEnder upgrade
Skipping (unsupported file extension): Jenkins
Skipping (unsupported file extension): DevOps
Skipping (unsupported file extension): 3D Printing for Bicycle
Skipping (unsupported file extension): Money
Skipping (unsupported file extension): Allergies
Skipping (unsupported file extension): Databases
Skipping (unsupported file extension): Tech Stacks
Skipping (unsupported file extension): Kubernetes Operator
Skipping (unsupported file extension): To Buy
Skipping (unsupported file extension): Amazon Web Services
Skipping (unsupported file extension): Networking
Skipping (unsupported file extension): Stateless
Skipping (unsupported file extension): Open Container Initiative
Skipping (unsupported file extension): Overtime
Skipping (unsupported file extension): Relational Database Service
Skipping (unsupported file extension): Interview Questions
Skipping (unsupported file extension): Load Balancing and Proxying
Skipping (unsupported file extension): AWS CLI
Skipping (unsupported file extension): Continuous Integration and Deployment
Skipping (unsupported file extension): REST-API
Skipping (unsupported file extension): 3D Printing
Skipping (unsupported file extension): Kubernetes Deploy With Jenkins
Skipping (unsupported file extension): Linux Shell
Skipping (unsupported file extension): Physical Health
Skipping (unsupported file extension): Clothes Buy List
Skipping (unsupported file extension): URL
Skipping (unsupported file extension): sed
Skipping (unsupported file extension): Linux
Skipping (unsupported file extension): OSI/TCP-IP
Skipping (unsupported file extension): Watch
Skipping (unsupported file extension): To read lists
Skipping (unsupported file extension): Linux vs Windows
Skipping (unsupported file extension): Stash
Skipping (unsupported file extension): Monitoring
Skipping (unsupported file extension): Linux File Systems
Skipping (unsupported file extension): ArgoCD
Skipping (unsupported file extension): Stateful
Skipping (unsupported file extension): Sleep 2hr a day
Skipping (unsupported file extension): Distributed Lock
Skipping (unsupported file extension): System Design
Skipping (unsupported file extension): Golang
Skipping (unsupported file extension): Drugs
Skipping (unsupported file extension): Side-hustles
Skipping (unsupported file extension): Useful pics
Skipping (unsupported file extension): AWS Certified Cloud Practicioner (CLF-C01)
Skipping (unsupported file extension): Mental Health Buy List
Skipping (unsupported file extension): Site Reliability Engineering
Skipping (unsupported file extension): awk
Skipping (unsupported file extension): Firewall
Skipping (unsupported file extension): Security
Skipping (unsupported file extension): Orchestration
✅ Done loading.
✅ Done converting.
❯ ls output/
❯
```

This is my directory structure (inside input dir):
```console
❯ pwd
/home/atimofeev/repos/orgroam_to_obsidian/input
❯ lt --level 3
.
├── roam
│  ├── .git
│  │  ├── branches
│  │  ├── hooks
│  │  ├── info
│  │  ├── logs
│  │  ├── objects
│  │  ├── refs
│  │  ├── AUTO_MERGE
│  │  ├── COMMIT_EDITMSG
│  │  ├── config
│  │  ├── description
│  │  ├── FETCH_HEAD
│  │  ├── HEAD
│  │  ├── index
│  │  ├── ORIG_HEAD
│  │  └── packed-refs
│  ├── doc
│  │  └── Criteria-Artem-Timofeev-Workplace-Insights.pdf
│  ├── health
│  │  ├── allergies.org
│  │  ├── drugs.org
│  │  ├── health.org
│  │  ├── mental_health.org
│  │  ├── mental_health_tests.org
│  │  └── physical_health.org
│  ├── img
│  │  ├── 5min-plank.png
│  │  ├── 10-main-data-structures.png
│  │  ├── 16P-INTP.png
│  │  ├── api-arch-styles.png
│  │  ├── api-gateway.png
│  │  ├── api-performance.png
│  │  ├── api-protocols.png
│  │  ├── api-security.png
│  │  ├── api-testing.png
│  │  ├── bash-shell-kb-cs.png
│  │  ├── boot-failure-troubleshoot.png
│  │  ├── boot-failure-troubleshoot2.png
│  │  ├── cache-systems.png
│  │  ├── cdn.png
│  │  ├── cidr.png
│  │  ├── cloud-main-services.png
│  │  ├── cloud-models.png
│  │  ├── cloud-native-arch.png
│  │  ├── cloud-premise-vpn-tunnel.png
│  │  ├── company-size-tooling.png
│  │  ├── data-structures-daily-life.png
│  │  ├── data-terms.png
│  │  ├── data-warehouse-vs-data-lake.png
│  │  ├── db-data-structures.png
│  │  ├── design-trends.png
│  │  ├── devops-sre-platform-eng.png
│  │  ├── devops-toolset.png
│  │  ├── docker-cli-cheat-sheet.png
│  │  ├── emerging-technology-2012-beyond.png
│  │  ├── ender3-spi.png
│  │  ├── firewall-sysdesign-overview.png
│  │  ├── font-selection.png
│  │  ├── fw-rv-proxy.png
│  │  ├── git-cheat-sheet.png
│  │  ├── git-commands.png
│  │  ├── git-merge.png
│  │  ├── gitflow.png
│  │  ├── howto-concentrate.png
│  │  ├── http-header.png
│  │  ├── https-how-works.png
│  │  ├── hybrid-cloud.png
│  │  ├── inter-proc-communication.png
│  │  ├── k8s-api-structure.png
│  │  ├── k8s-basic-arch.png
│  │  ├── k8s-cni-providers.png
│  │  ├── k8s-resources-map.png
│  │  ├── linkedin-graphql.png
│  │  ├── linux-observability-tools.png
│  │  ├── microservices-best-practices.png
│  │  ├── monorepo-vs-microrepo.png
│  │  ├── movie-directors-iceberg.png
│  │  ├── movie-torture.png
│  │  ├── netflix-arch.png
│  │  ├── netflix-dbs.png
│  │  ├── osi-model.png
│  │  ├── osi-vs-tcpip.png
│  │  ├── other-ways-to-say-english.png
│  │  ├── postresql-arch.png
│  │  ├── postresql-cluster.png
│  │  ├── regex-cheat-sheet.png
│  │  ├── rest-vs-graphql.png
│  │  ├── schulte-table.png
│  │  ├── service-deployment-strategies.png
│  │  ├── shopify-resilience.png
│  │  ├── slack-message-journey.png
│  │  ├── sql-vs-nosql-in-cloud.png
│  │  ├── stateless-vs-stateful.png
│  │  ├── systemd-vs-sysvinit.png
│  │  ├── text-encoding-breakdown.png
│  │  ├── top-100-fantasy-books-guide.png
│  │  ├── top-caching-strategies.png
│  │  ├── train-to-run-long.png
│  │  ├── twitter-1.0-tech-stack.png
│  │  ├── url-structure.png
│  │  ├── vim-cheat-sheet.png
│  │  ├── vim-visual-cheat-sheet.png
│  │  ├── visual-morse-code.png
│  │  ├── vpc.png
│  │  ├── wallpaper-alex-grey-kiss.png
│  │  ├── wallpaper-dark-panelki.png
│  │  ├── wallpaper-dark-shore.png
│  │  └── wallpaper-justin-zoll-lGlutamine.png
│  ├── leisure
│  │  ├── 3dp.org
│  │  ├── bike.org
│  │  ├── books.org
│  │  ├── ender_3_bootloader.org
│  │  ├── games.org
│  │  ├── klackender_upgrade.org
│  │  ├── leisure.org
│  │  ├── music.org
│  │  └── watch.org
│  ├── money
│  │  ├── debt.org
│  │  ├── money.org
│  │  └── subscriptions.org
│  ├── stash
│  │  ├── ideas.org
│  │  ├── sites.org
│  │  ├── stash.org
│  │  ├── stash_tools.org
│  │  ├── to_buy.org
│  │  ├── useful_pics.org
│  │  └── wallpaper_pics.org
│  ├── tech
│  │  ├── ai.org
│  │  ├── ai_tools.org
│  │  ├── amazon_web_services.org
│  │  ├── ansible.org
│  │  ├── argocd.org
│  │  ├── autogpt.org
│  │  ├── awk.org
│  │  ├── aws_best_practices.org
│  │  ├── aws_billing_budget_alerts_and_costs.org
│  │  ├── aws_cli.org
│  │  ├── AWS_Cloud_practicioner.org
│  │  ├── bash.org
│  │  ├── caching.org
│  │  ├── cgroups.org
│  │  ├── chatgpt_prompts.org
│  │  ├── client_server_communication.org
│  │  ├── cloud.org
│  │  ├── content_delivery_network.org
│  │  ├── continuous_integration_and_deployment.org
│  │  ├── data_structures.org
│  │  ├── databases.org
│  │  ├── deployment_strategies.org
│  │  ├── devops.org
│  │  ├── devsecops.org
│  │  ├── distributed_lock.org
│  │  ├── dns.org
│  │  ├── docker.org
│  │  ├── elastic_block_storage.org
│  │  ├── firewall.org
│  │  ├── functional_programming.org
│  │  ├── github_actions.org
│  │  ├── gitlab_ci.org
│  │  ├── gitops.org
│  │  ├── golang.org
│  │  ├── graph_databases.org
│  │  ├── helm.org
│  │  ├── http.org
│  │  ├── http_status_codes.org
│  │  ├── hybrid_cloud.org
│  │  ├── iam_core_concepts.org
│  │  ├── infrastructure_as_code.org
│  │  ├── interview_questions.org
│  │  ├── jenkins.org
│  │  ├── kubernetes.org
│  │  ├── kubernetes_deploy_with_jenkins.org
│  │  ├── kubernetes_essentials.org
│  │  ├── kubernetes_in_3_5h.org
│  │  ├── kubernetes_operator.org
│  │  ├── leaky_bucket_algorithm.org
│  │  ├── linux.org
│  │  ├── linux_file_systems.org
│  │  ├── linux_kernel.org
│  │  ├── linux_processes.org
│  │  ├── linux_shell.org
│  │  ├── linux_system_services.org
│  │  ├── linux_under_the_hood.org
│  │  ├── linux_vs_windows.org
│  │  ├── load_balancing_and_proxying.org
│  │  ├── logic_programming.org
│  │  ├── lxc.org
│  │  ├── managed_k8s_in_cloud.org
│  │  ├── mastering_aws_cloudformation.org
│  │  ├── mongodb.org
│  │  ├── monitoring.org
│  │  ├── namespaces.org
│  │  ├── network_troubleshooting.org
│  │  ├── networking.org
│  │  ├── object_oriented_programming.org
│  │  ├── obsidian.org
│  │  ├── open_container_initiative.org
│  │  ├── operation_systems.org
│  │  ├── orchestration.org
│  │  ├── org-mode-unicorn.svg
│  │  ├── osi_tcp_ip.org
│  │  ├── postgresql.org
│  │  ├── practices.org
│  │  ├── pre_signed_urls.org
│  │  ├── procedural_programming.org
│  │  ├── programming.org
│  │  ├── programming_design_patterns.org
│  │  ├── prometheus.org
│  │  ├── python.org
│  │  ├── python_libs.org
│  │  ├── reactive_programming.org
│  │  ├── redis.org
│  │  ├── regular_expressions.org
│  │  ├── relational_database_service.org
│  │  ├── relational_databases.org
│  │  ├── rest_api.org
│  │  ├── security.org
│  │  ├── sed.org
│  │  ├── simple_queue_service.org
│  │  ├── simple_storage_service.org
│  │  ├── site_reliability_engineering.org
│  │  ├── stateful.org
│  │  ├── stateless.org
│  │  ├── structured_programming.org
│  │  ├── subnets_cidr.org
│  │  ├── system_design.org
│  │  ├── tech_projects.org
│  │  ├── tech_stack.org
│  │  ├── tech_stacks.org
│  │  ├── terraform.org
│  │  ├── text_manipulation.org
│  │  ├── thundering_herd.org
│  │  ├── url.org
│  │  ├── version_control.org
│  │  ├── vim.org
│  │  └── virtual_private_network.org
│  ├── templates
│  │  └── cover-letter.org
│  ├── uncat
│  │  ├── sleep_2hr_a_day.org
│  │  ├── tentatrice_jewelry.org
│  │  └── uncategorized.org
│  ├── work
│  │  ├── 3d_printing_for_bicycle.org
│  │  ├── interviews.org
│  │  ├── meetings.org
│  │  ├── overtime.org
│  │  ├── side_hustles.org
│  │  └── work.org
│  ├── .organice-config.json
│  ├── .orgids
│  └── README.org
├── .keep
└── org-roam.db
```

I use README.org as index file for all of the subdirectories.

```console
❯ ll
drwxr-xr-x    - atimofeev 30 Jan 14:53 doc
drwxr-xr-x    - atimofeev 30 Jan 14:53 health
drwxr-xr-x    - atimofeev 30 Jan 14:53 img
drwxr-xr-x    - atimofeev  5 Sep 11:12 leisure
drwxr-xr-x    - atimofeev 30 Jan 14:53 money
drwxr-xr-x    - atimofeev 30 Jan 14:53 stash
drwxr-xr-x    - atimofeev 30 Jan 22:48 tech
drwxr-xr-x    - atimofeev 30 Jan 14:53 templates
drwxr-xr-x    - atimofeev 30 Jan 14:53 uncat
drwxr-xr-x    - atimofeev 30 Jan 14:53 work
.rw-r--r-- 3.6k atimofeev  5 Sep 11:12 README.org
```

I'm using latest commit, which should support subdirectories.

Not sure if this matters, but my org-directory is "~/repos/org".

How can I help debug this issue?

**Comment by atimofeev** [comment]
Contents of my org-roam.db: https://gist.github.com/atimofeev/f26a024fd8de8fe574b5248dc01f68ab

**Comment by bloodstiller** [comment]
> Contents of my org-roam.db: https://gist.github.com/atimofeev/f26a024fd8de8fe574b5248dc01f68ab

Did you get this fixed? Tried myself and the same issue. Even using a completely flat directory it would not work.

**Comment by driftcrow** [comment]
the same issue

**Comment by goshatch** [comment]
Hi folks, I apologise for being very late looking at these issues. I made a note for myself to look at them in detail when I'm back from the holidays (around Jan. 5), and I'll provide a fix where I can.

Thank you for your patience!

**Comment by goshatch** [comment]
Hello! I've just pushed a new commit that adds some debugging code to the script.

Could you please pull the latest version, and give a try to running the script with the debug flag, like this:

```sh
$ ./convert.rb --debug
```
This should print some useful information that should help us resolve the issues that are happening here.

Thanks again for your patience!

**Comment by bloodstiller** [comment]
> Hello! I've just pushed a new commit that adds some debugging code to the script.
> 
> Could you please pull the latest version, and give a try to running the script with the debug flag, like this:
> 
> ```shell
> $ ./convert.rb --debug
> ```
> 
> This should print some useful information that should help us resolve the issues that are happening here.
> 
> Thanks again for your patience!

Hey man, thanks for doing this. So I have done this and I think my issue is that the script does not like org roam files linked as headers within files 

```
Skipping (unsupported file extension): Wordpress
	input file: input/roam/
	file relative to roam dir:
	extension:
Skipping (unsupported file extension): TODOLIST: [/]
	input file: input/roam/
	file relative to roam dir:
	extension:
Skipping (unsupported file extension): If Windows Server 2008, Windows 7 or 8 is found:
	input file: input/roam/
	file relative to roam dir:
	extension:
```

Do you have any test data we could put through it? If not I can create some but will be a little while before I can get to it.

**Comment by goshatch** [comment]
Wow, yes. These notes don't seem to be represented by any actual files on disk -- we don't support this case at all.

Could you paste a file that contains one or more of the notes in your log above? (please take care to remove any sensitive content)

**Comment by RandomWalk90** [comment]
@goshatch  Hi, I have met the same issue and fixed it.
The problem is where is your origin roam files. In the convert.rb 27L, the script wants to get files' name by split path with 'roam', but,  in my case , the file path does not contain 'roam'.
change 'roam' to your path, it will work.

**Comment by atimofeev** [comment]
I've changed `roam/` to actual filepath from `org-roam.db` and now it works!
```diff
-    @roam_file ||= "#{@row.file.partition('roam/').last}"
+    @roam_file ||= "#{@row.file.partition('/home/atimofeev/repos/org/').last}"
```

**Comment by goshatch** [comment]
Hi @RandomWalk90 and @atimofeev, thank you so much for your help! 

I just pushed a commit that should fix this: you can now run the script with an `--roam-root` flag to specify your root org-roam directory. Could you please check if this works, and reopen this issue if not?

**Comment by RandomWalk90** [comment]
it's still an error:
```
./convert.rb:14:in `initialize': wrong number of arguments (given 3, expected 1) (ArgumentError)
```

**Comment by bloodstiller** [comment]
> it's still an error:
> ```
> ./convert.rb:14:in `initialize': wrong number of arguments (given 3, expected 1) (ArgumentError)
> ```

Can confirm same issue when passing roam db argument. Have personally tried in quotation marks, without quotation marks, full paths etc.

**Comment by goshatch** [comment]
@RandomWalk90 @bloodstiller, sorry, I made a mistake in my previous push. Should be fixed now.

**Comment by bloodstiller** [comment]
```
🕙 17:25:56 zsh ❯ ./convert.rb --roam-root /home/martin/Dropbox/40-49_Career/40-Career-ZK/
./convert.rb:69:in `initialize': unknown keyword: :roam_root (ArgumentError)
	from ./convert.rb:157:in `new'
	from ./convert.rb:157:in `<main>'
```
The issue is that while you've added the `--roam-root` option to the OptionParser, the Converter class initialization doesn't accept `:roam_root` as a parameter - it's using `org_root` instead.

Made below change and seem to have worked

```diff
  class Converter
-   def initialize(debug: false, org_root: nil)
+   def initialize(debug: false, roam_root: nil)
      @debug = debug
      @notes = {}
      # ... other code ...
      results.each do |result|
-       note = Note.new(result, debug: debug, org_root: org_root)
+       note = Note.new(result, debug: debug, org_root: roam_root)
        if File.extname(note.input_file) != '.org'
```
```diff
  def roam_file
    @roam_file ||= "#{@row.file.partition(@org_root).last}"
  end

  def input_file
-   @input_file ||= "input/roam/#{roam_file}"
+   @input_file ||= File.join(@org_root, roam_file)
  end

  def title
```

**Comment by goshatch** [comment]
Sorry, folks. I did this fix on my phone, rushed too much, and forgot I had renamed a var half way through. I've pushed some fixes now. Thanks for your patience!
