### ISSUE TITLE
/Library/Ruby/Gems/2.6.0/gems/pandoc-ruby-2.1.7/lib/pandoc-ruby.rb:306:in `execute': pandoc: input/roam/: withBinaryFile: does not exist (No such file or directory) (RuntimeError)

### ISSUE THREAD

**Issue by gatlee** [goshatch/orgroam_to_obsidian#4]
Followed all the steps. Running convert.rb fails
```
❯ ./convert.rb                                                                                                                                                    ~/Documents/sources/orgroam_to_obsidian
/Library/Ruby/Gems/2.6.0/gems/pandoc-ruby-2.1.7/lib/pandoc-ruby.rb:306:in `execute': pandoc: input/roam/: withBinaryFile: does not exist (No such file or directory) (RuntimeError)
	from /Library/Ruby/Gems/2.6.0/gems/pandoc-ruby-2.1.7/lib/pandoc-ruby.rb:275:in `execute_pandoc'
	from /Library/Ruby/Gems/2.6.0/gems/pandoc-ruby-2.1.7/lib/pandoc-ruby.rb:269:in `convert_string'
	from /Library/Ruby/Gems/2.6.0/gems/pandoc-ruby-2.1.7/lib/pandoc-ruby.rb:205:in `convert'
	from /Library/Ruby/Gems/2.6.0/gems/pandoc-ruby-2.1.7/lib/pandoc-ruby.rb:241:in `block (2 levels) in <class:PandocRuby>'
	from ./convert.rb:39:in `input_file_to_md'
	from ./convert.rb:17:in `initialize'
	from ./convert.rb:61:in `new'
	from ./convert.rb:61:in `block in initialize'
	from ./convert.rb:60:in `each'
	from ./convert.rb:60:in `initialize'
	from ./convert.rb:96:in `new'
	from ./convert.rb:96:in `<main>'
```

**Comment by CharlesEkkel** [comment]
Could you print out the contents of `input` and `input/roam`? If I were to guess, it seems like the roam folder is missing? Perhaps you've copied the contents of the roam folder directly into `input/`?

**Comment by goshatch** [comment]
I'm going to close this issue for now. If anyone else runs into this issue, please let me know and I will reopen it.

**Comment by hakanserce** [comment]
I ran into the same issue, and in my case the problem was this line https://github.com/goshatch/orgroam_to_obsidian/blob/7262f2344a840f52e30bef981f7f896842900ff8/convert.rb#L24

Note that here the code doesn't only expect the files to be under `input/roam` folder, but also expects the original files to be under a `roam` subfolder somewhere. In my case, my files where under a differently named folder, so changing that in the code fixed the issue. Taking original org-roam folder path as an argument and using that instead of expecting the name to be `roam` would fix the issue.

**Comment by goshatch** [comment]
Thank you @hakanserce! Would you be willing to prepare a PR for this?

**Comment by goshatch** [comment]
This should have been fixed in the latest commit. If your `org-roam` directory is not the default `~/org-roam`, please pass it as a command line argument:

```sh
$ ./convert.rb --roam-root "~/org/roam"
```
