### ISSUE TITLE
DB fails to initialize both in the docker image and with the code 

### ISSUE THREAD

**Issue by tonicebrian** [goshatch/orgroam_to_obsidian#8]
Running your startup scripts takes me to this error both in code and Docker image:

```
❯ ./convert.rb
/usr/lib/ruby/vendor_ruby/sqlite3/database.rb:147:in `initialize': no such table: nodes (SQLite3::SQLException)
        from /usr/lib/ruby/vendor_ruby/sqlite3/database.rb:147:in `new'
        from /usr/lib/ruby/vendor_ruby/sqlite3/database.rb:147:in `prepare'
        from /usr/lib/ruby/vendor_ruby/sqlite3/database.rb:193:in `execute'
        from ./convert.rb:59:in `initialize'
        from ./convert.rb:100:in `new'
        from ./convert.rb:100:in `<main>'
```

**Comment by goshatch** [comment]
Hi folks, I apologise for being very late looking at these issues. I made a note for myself to look at them in detail when I'm back from the holidays (around Jan. 5), and I'll provide a fix where I can.

Thank you for your patience!

**Comment by goshatch** [comment]
Hi @tonicebrian! I've just pushed a new commit that adds some debugging code to the script.

Could you please pull the latest version, and give a try to running the script with the debug flag, like this:

```sh
$ ./convert.rb --debug
```

This should print some useful information that should help us resolve the issues that are happening here.

Thanks again for your patience!

**Comment by tonicebrian** [comment]
Sorry but I manually migrated all my notes and now I haven't an org roam installation to test.
